export DOCKER_REGISTRY_SERVER=https://index.docker.io/v1/
export DOCKER_USER=docker7399
export DOCKER_EMAIL=Priyanka.Das@mindtree.com
export DOCKER_PASSWORD=Ult1m@te

kubectl create secret docker-registry myregistrykey --docker-server=$DOCKER_REGISTRY_SERVER --docker-username=$DOCKER_USER --docker-password=$DOCKER_PASSWORD --docker-email=$DOCKER_EMAIL

apiVersion: v1
kind: Pod
metadata:
  name: helloworld
spec:
  containers:
    - name: helloworld
      image: index.docker.io/docker7399/helloworld:latest
      imagePullPolicy: Always
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
  imagePullSecrets:
    - name: myregistrykey
             

